### ISSUE TITLE
Error during training in evaluation

### ISSUE THREAD

**Issue by liqikai9** [sail-sg/mvp#10]
Hi, I encountered the following error when training the first epoch in the evaluation. Could you help find out the problem? Thanks in anvance.

```
INFO:core.function:Test: [200/323]      Time: 0.178s (0.291s)   Speed: 28.1 samples/s   Data: 0.000s (0.055s)   Memory 465635328.0
Traceback (most recent call last):
  File "run/train_3d.py", line 334, in <module>
    main()
  File "run/train_3d.py", line 260, in main
    final_output_dir, thr, num_views=num_views)
  File "/mnt/lustre/liqikai.vendor/open_mmlab/pose3d/mvp/lib/core/function.py", line 161, in validate_3d
    for i, (inputs, meta) in enumerate(loader):
  File "/mnt/lustre/liqikai.vendor/anaconda3/envs/pt180cu111py37mmcv1317/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/mnt/lustre/liqikai.vendor/anaconda3/envs/pt180cu111py37mmcv1317/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1179, in _next_data
    return self._process_data(data)
  File "/mnt/lustre/liqikai.vendor/anaconda3/envs/pt180cu111py37mmcv1317/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1225, in _process_data
    data.reraise()
  File "/mnt/lustre/liqikai.vendor/anaconda3/envs/pt180cu111py37mmcv1317/lib/python3.7/site-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
ValueError: Caught ValueError in DataLoader worker process 1.
Original Traceback (most recent call last):
  File "/mnt/lustre/liqikai.vendor/anaconda3/envs/pt180cu111py37mmcv1317/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/mnt/lustre/liqikai.vendor/anaconda3/envs/pt180cu111py37mmcv1317/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/mnt/lustre/liqikai.vendor/anaconda3/envs/pt180cu111py37mmcv1317/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/mnt/lustre/liqikai.vendor/open_mmlab/pose3d/mvp/lib/dataset/panoptic.py", line 257, in __getitem__
    i, m = super().__getitem__(self.num_views * idx + k)
ValueError: too many values to unpack (expected 2)

```

**Comment by twangnh** [comment]
hi, please pull from the repo to get the tiny fix update

**Comment by liqikai9** [comment]
I have run through the code. This issue is due to the missing part in the dataset.
