### ISSUE TITLE
ModuleNotFoundErrorModuleNotFoundError: : No module named 'lib.core'No module named 'lib.core'

### ISSUE THREAD

**Issue by Taylorminer** [sail-sg/mvp#8]
I meet this error. 
Traceback (most recent call last):
  File "run/validate_3d.py", line 35, in <module>
    from lib.core.config import config
ModuleNotFoundError: No module named 'lib.core'
/media/chen-group/9400EADF00EAC778/cy/mvp-main
Traceback (most recent call last):
  File "run/validate_3d.py", line 35, in <module>
    from lib.core.config import config
ModuleNotFoundError: No module named 'lib.core'
/media/chen-group/9400EADF00EAC778/cy/mvp-main
Traceback (most recent call last):
  File "run/validate_3d.py", line 35, in <module>
    from lib.core.config import config
ModuleNotFoundError: No module named 'lib.core'
/media/chen-group/9400EADF00EAC778/cy/mvp-main
Traceback (most recent call last):
  File "run/validate_3d.py", line 35, in <module>
    from lib.core.config import config
ModuleNotFoundError: No module named 'lib.core'
/media/chen-group/9400EADF00EAC778/cy/mvp-main
Traceback (most recent call last):
  File "run/validate_3d.py", line 35, in <module>
    from lib.core.config import config
ModuleNotFoundError: No module named 'lib.core'
/media/chen-group/9400EADF00EAC778/cy/mvp-main
Traceback (most recent call last):
  File "run/validate_3d.py", line 35, in <module>
    from lib.core.config import config
ModuleNotFoundError: No module named 'lib.core'
/media/chen-group/9400EADF00EAC778/cy/mvp-main
/media/chen-group/9400EADF00EAC778/cy/mvp-main
Traceback (most recent call last):
Traceback (most recent call last):
  File "run/validate_3d.py", line 35, in <module>
  File "run/validate_3d.py", line 35, in <module>
        from lib.core.config import configfrom lib.core.config import config

ModuleNotFoundErrorModuleNotFoundError: : No module named 'lib.core'No module named 'lib.core'

Can you tell me how to solve it ?

**Comment by liqikai9** [comment]
I think you can refer to #5 and add lib to the PYTHONPATH. For example, add the following line in `run\_init_paths.py`

```
add_path(${MVP_ROOT_FOLDER}/lib)
```

**Comment by Taylorminer** [comment]
> 

Thanks for your reply. There is 'add_path(lib_path)' in  _init_paths.py. Is it necessary to add 'add_path(${MVP_ROOT_FOLDER}/lib)'?

**Comment by liqikai9** [comment]
I think it is necessary. You can try it.
