### ISSUE TITLE
Problem about creating logger

### ISSUE THREAD

**Issue by liqikai9** [sail-sg/mvp#9]
Hi, thanks for your great work. I tried to rerun your code, but I encounter a problem as follows. I wonder whether it is related to multiprocessing module. 

```
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "run/train_3d.py", line 329, in <module>
  File "run/train_3d.py", line 329, in <module>
  File "run/train_3d.py", line 329, in <module>
  File "run/train_3d.py", line 329, in <module>
  File "run/train_3d.py", line 329, in <module>
  File "run/train_3d.py", line 329, in <module>
Traceback (most recent call last):
  File "run/train_3d.py", line 329, in <module>
    main()
  File "run/train_3d.py", line 138, in main
            main()main()main()


    main()  File "run/train_3d.py", line 138, in main
main()main()  File "run/train_3d.py", line 138, in main

  File "run/train_3d.py", line 138, in main


  File "run/train_3d.py", line 138, in main
  File "run/train_3d.py", line 138, in main
  File "run/train_3d.py", line 138, in main
    config, args.cfg, 'train')
  File "/mnt/lustre/liqikai.vendor/open_mmlab/pose3d/mvp/lib/utils/utils.py", line 43, in create_logger
            config, args.cfg, 'train')config, args.cfg, 'train')config, args.cfg, 'train')


  File "/mnt/lustre/liqikai.vendor/open_mmlab/pose3d/mvp/lib/utils/utils.py", line 43, in create_logger
  File "/mnt/lustre/liqikai.vendor/open_mmlab/pose3d/mvp/lib/utils/utils.py", line 43, in create_logger
  File "/mnt/lustre/liqikai.vendor/open_mmlab/pose3d/mvp/lib/utils/utils.py", line 43, in create_logger
    config, args.cfg, 'train')
    config, args.cfg, 'train')  File "/mnt/lustre/liqikai.vendor/open_mmlab/pose3d/mvp/lib/utils/utils.py", line 43, in create_logger

  File "/mnt/lustre/liqikai.vendor/open_mmlab/pose3d/mvp/lib/utils/utils.py", line 43, in create_logger
    config, args.cfg, 'train')
  File "/mnt/lustre/liqikai.vendor/open_mmlab/pose3d/mvp/lib/utils/utils.py", line 43, in create_logger
    root_output_dir.mkdir()
  File "/mnt/lustre/liqikai.vendor/anaconda3/envs/pt180cu111py37mmcv1317/lib/python3.7/pathlib.py", line 1273, in mkdir
    root_output_dir.mkdir()
    root_output_dir.mkdir()  File "/mnt/lustre/liqikai.vendor/anaconda3/envs/pt180cu111py37mmcv1317/lib/python3.7/pathlib.py", line 1273, in mkdir

  File "/mnt/lustre/liqikai.vendor/anaconda3/envs/pt180cu111py37mmcv1317/lib/python3.7/pathlib.py", line 1273, in mkdir
    root_output_dir.mkdir()
  File "/mnt/lustre/liqikai.vendor/anaconda3/envs/pt180cu111py37mmcv1317/lib/python3.7/pathlib.py", line 1273, in mkdir
    root_output_dir.mkdir()
    root_output_dir.mkdir()
  File "/mnt/lustre/liqikai.vendor/anaconda3/envs/pt180cu111py37mmcv1317/lib/python3.7/pathlib.py", line 1273, in mkdir
            self._accessor.mkdir(self, mode)    self._accessor.mkdir(self, mode)
self._accessor.mkdir(self, mode)self._accessor.mkdir(self, mode)


self._accessor.mkdir(self, mode)
self._accessor.mkdir(self, mode)
FileExistsErrorFileExistsErrorFileExistsErrorFileExistsErrorFileExistsErrorFileExistsError    self._accessor.mkdir(self, mode)
FileExistsError: : : : [Errno 17] File exists: '/mnt/lustre/liqikai.vendor/open_mmlab/pose3d/mvp/output': [Errno 17] File exists: '/mnt/lustre/liqikai.vendor/open_mmlab/pose3d/mvp/output': [Errno 17] File exist
s: '/mnt/lustre/liqikai.vendor/open_mmlab/pose3d/mvp/output'[Errno 17] File exists: '/mnt/lustre/liqikai.vendor/open_mmlab/pose3d/mvp/output': [Errno 17] File exists: '/mnt/lustre/liqikai.vendor/open_mmlab/pose
3d/mvp/output'[Errno 17] File exists: '/mnt/lustre/liqikai.vendor/open_mmlab/pose3d/mvp/output'[Errno 17] File exists: '/mnt/lustre/liqikai.vendor/open_mmlab/pose3d/mvp/output'

```

**Comment by twangnh** [comment]
could you try delete the `output` directory

**Comment by liqikai9** [comment]
I have tried deleting the `output` directory. But it didn't work. So I just hard-coded the `final_output_dir` in the `train_3d.py` and I also set the logger right in the `train_3d.py`, thus without calling the `create_logger()` function and it worked.
